sudo: false
language: generic
notifications:
  email: false
git:
  depth: 5
cache:
  directories:
    - ${HOME}/.roswell
    - ${HOME}/.config/common-lisp
addons:
  apt:
    packages:
      - libc6-i386
      - default-jre
env:
  matrix:
    - LISP=sbcl-bin
    - LISP=abcl
    - LISP=allegro
    - LISP=ccl
    - LISP=clasp
    - LISP=clisp
    - LISP=cmu
    - LISP=ecl
    - LISP=mkcl
matrix:
  allow_failures:
    - env: LISP=abcl
    - env: LISP=allegro
    - env: LISP=ccl
    - env: LISP=clasp
    - env: LISP=clisp
    - env: LISP=cmu
    - env: LISP=ecl
    - env: LISP=mkcl
install:
  - export ROSWELL_BRANCH=release
  - export ROSWELL_INSTALL_DIR=${HOME}/.roswell
  - export PATH=${ROSWELL_INSTALL_DIR}/bin:${PATH}
  - travis_retry curl -L https://raw.githubusercontent.com/roswell/roswell/${ROSWELL_BRANCH}/scripts/install-for-ci.sh | sh
before_script:
  - ros version
  - ros config
script:
  - make test
